name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: aryanariman/github-actions-workflows/.github/workflows/python-build-release.yml@main

    with:
      files: |
        TextMerger&RestoreTool.py
        TextMerger&RestoreTool-DirEdition.py

      python-version: "3.13"